---
# - name: update web, nfs and db servers
#   hosts: webservers, nfs
#   remote_user: ec2-user
#   become: yes
#   become_user: root
#   tasks:
#   - name: ensure wireshark is at the latest version
#     yum:
#       name: wireshark
#       state: latest

# - name: update LB server
#   hosts: lb, db
#   remote_user: ubuntu
#   become: yes
#   become_user: root
#   tasks:
#   - name: ensure wireshark is at the latest version
#     apt:
#       name: wireshark
#       state: latest

- name: install softwares
  hosts: db
  become: true
  tasks:
    
    - name: installing and updating repos
      dnf: update_cache=yes state=present

    - name: print the hostname
      command: hostname

    - name: install base packages
      ansible.builtin.yum:
        update_cache: yes

    - name: Install dependencies for mySQL Python
      yum:
        name:
          - python3
          - git
          - python3-pip
          #  - tree
          #   - python3-pip
        state: present

    - name: Install the Python MySQLB module
      pip:
        name:
          - mysql-connector-python
          - PyMySQL

    - name: create a test file
      file:
        path: /home/test
        state: touch